### ISSUE TITLE
Exception because event for event listener is not defined

### ISSUE THREAD

**Issue by rintisch** [georgringer/autoswitchtolistview#12]
When updating to `2.0.5` the error

> **(1/1) #1563217364 InvalidArgumentException**
>
>Service tag "event.listener" requires an event attribute to be defined, missing in: GeorgRinger\Autoswitchlistview\EventListener\PageModuleListener

is thrown. 
![image](https://github.com/georgringer/autoswitchtolistview/assets/44193208/913b5119-766b-4543-bd36-59b04f38e48d)

The event listener must have an event to listen to:

https://github.com/georgringer/autoswitchtolistview/blob/8de09e5790df80506235041eb5e70374339bf3c1/Configuration/Services.yaml#L10-L13

**Comment by oliverklee** [comment]
The problem also occurs in an installation of mine: It's using Composer with TYPO3 10LTS, and the problem occurs when running `typo3cms database:updateschema` via Deployer, but strangely not when I run this locally. (For Deployer, I'm using only the production dependencies, not the development Composer dependencies. Maybe this is related.)

**Comment by rintisch** [comment]
For it happens locally and with composer, also using TYPO3 10.

**Comment by georgringer** [comment]
ah I guess this is 10 lts only. so you should stick to 2.0.4, I will probably remove the version and release a new one with changed dependencies

**Comment by oliverklee** [comment]
I would recommend keeping the (broken) 2.0.5 and releasing a fixed 2.0.6. Otherwise, we’ll have two version numbers referencing different versions, and there is no way to update from a broken 2.0.5 to a fixed 2.0.6 (because you cannot update from 2.0.5 to 2.0.5).

**Comment by oliverklee** [comment]
That is assuming that it’s possible to fix the bug. And if it’s not, then I recommend using a different version number for the new release with different dependencies.

**Comment by Patta** [comment]
@georgringer for TYPO3 11, the tag 2.0.5 is still on [packagegist](https://packagist.org/packages/georgringer/autoswitchtolistview#2.0.5) and composer is not downgrading.

**Comment by georgringer** [comment]
has been removed there as well
