### ISSUE TITLE
Will there be support for TYPO3 v13?

### ISSUE THREAD

**Issue by SeBigBoss** [georgringer/autoswitchtolistview#17]
Just asking - because this is a really nice feature for editors!

**Comment by georgringer** [comment]
https://github.com/georgringer/autoswitchtolistview/releases/tag/3.0.1 thanks for asking. maybe you wanna donate some euros if you are using the ext

**Comment by SeBigBoss** [comment]
@georgringer danke für das schnelle Ändern!
Eine Bitte noch für Zeile 19: das ^  vor dem 13.4 hinzufügen, sonst klappt das nicht gut ;-)
Danke!

**Comment by georgringer** [comment]
mea culpa, fixed @SeBigBoss
