### ISSUE TITLE
Add TYPO3 9 LTS support

### ISSUE THREAD

**Issue by josefglatz** [georgringer/autoswitchtolistview#3]

**Comment by philippmaurer** [comment]
Hey @georgringer,
Thanks for the nice extension.
Is the current version with that fix stable on Typo3 9, or are there still things that need to be done? (Just asking because there is no official release of it)
If there are open tasks, i could support by coding some things.

**Comment by josefglatz** [comment]
@philippmaurer I use the ext in several TYPO3 9.5 instances.. let us know if it doesn't run as expected. Of course, an official release would be nice
